
### **_quarto.yml**
```yaml
project:
  type: website

website:
  title: "Página de Data Science"
  navbar:
    left:
      - text: "Início"
        href: index.qmd
      - text: "Projetos"
        href: projetos.qmd
      - text: "Contato"
        href: contato.qmd
  footer:
    text: "© 2024 Osvaldo Jeronymo"

format:
  html:
    theme: cosmo
    css: styles.css
